language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
gemfile: estormtech.com/Gemfile
script: sh -c 'cd ficonab.com && ruby test_app.rb && cd ../estormtech.com && ruby test_app.rb'
notifications:
  recipients:
    - scott.sproule@estormtech.com
  email:
    on_success: change
    on_failure: always

