source 'http://rubygems.org'


# rvmupdate gem 'rack', '1.4.5'
# rvm update gem 'rack-protection', '1.3.2'

gem 'sinatra' #rvm update, '1.3.6'
#gem 'rack', '1.4.5'   # fix bug on rack on deployment server--test to see if this can be removed.
gem 'nesta', '0.9.13'

group  :test do
  gem "rack-test"
end

# gem (RUBY_VERSION =~ /^1.9/) ? 'ruby-debug19': 'ruby-debug'
